os: linux
dist: bionic
sudo: required
language: node_js
node_js: "16.13.1"
addons:
  apt:
    sources: deadsnakes
    packages: python3.8
install: npm i && npm i -g truffle
script: truffle run coverage
after_script: bash <(curl -s https://codecov.io/bash)